Jusuf stuff
#!!!!!! WARNING: RUFF FAILED !!!!!!: 

#F811 Redefinition of unused `RBC2DG4R4ResARa1e5` from line 524
#   --> pySDC/projects/RayleighBenard/RBC3D_configs.py:529:7
#    |
#529 | class RBC2DG4R4ResARa1e5(RBC2DResA):
#    |       ^^^^^^^^^^^^^^^^^^ `RBC2DG4R4ResARa1e5` redefined here
#530 |     Tend = 100
#531 |     res = 64
#    |
#   ::: pySDC/projects/RayleighBenard/RBC3D_configs.py:524:7
#    |
#524 | class RBC2DG4R4ResARa1e5(RBC2DResA):
#    |       ------------------ previous definition of `RBC2DG4R4ResARa1e5` here
#525 |     Tend = 100
#526 |     res = 64
#    |
#help: Remove definition: `RBC2DG4R4ResARa1e5`
#
#F811 Redefinition of unused `RBC2DG4R4SDC23A10Ra1e6` from line 565
#   --> pySDC/projects/RayleighBenard/RBC3D_configs.py:578:7
#    |
#578 | class RBC2DG4R4SDC23A10Ra1e6(RBC2DM2K3A):
#    |       ^^^^^^^^^^^^^^^^^^^^^^ `RBC2DG4R4SDC23A10Ra1e6` redefined here
#579 |     Tend = 50
#580 |     res = 128
#    |
#   ::: pySDC/projects/RayleighBenard/RBC3D_configs.py:565:7
#    |
#565 | class RBC2DG4R4SDC23A10Ra1e6(RBC2DM2K3A):
#    |       ---------------------- previous definition of `RBC2DG4R4SDC23A10Ra1e6` here
#566 |     Tend = 100
#567 |     res = 64
#    |
#help: Remove definition: `RBC2DG4R4SDC23A10Ra1e6`
#
#Found 2 errors.: