Forgot a couple
#!!!!!!!!!! WARNING: FLAKEHEAVEN FAILED !!!!!!!!!!: 

#/Users/thomasbaumann/Documents/pySDC/pySDC/playgrounds/FEniCSx/HeatEquation_1D_FEniCSx_matrix_forced.py:8:1: F811 redefinition of unused 'plt' from line 3
#from matplotlib import pyplot as plt
#^
#1     F811 redefinition of unused 'plt' from line 3
#1: