Small changes to spsolve timings script
#!!!!!! WARNING: FLAKEHEAVEN FAILED !!!!!!: 

#Missing plugins: 
#flake8-bugbear
#flake8-comprehensions
#pySDC/projects/GPU/sparse_GPU_analysis/spsolve_timings.py:7:14: F811 redefinition of unused 'sp' from line 2
#def gen_data(sp, xp, N):
#             ^
#pySDC/projects/GPU/sparse_GPU_analysis/spsolve_timings.py:7:18: F811 redefinition of unused 'xp' from line 3
#def gen_data(sp, xp, N):
#                 ^
#pySDC/projects/GPU/sparse_GPU_analysis/spsolve_timings.py:13:29: F811 redefinition of unused 'xp' from line 3
#def single_test_dense(A, y, xp):
#                            ^
#pySDC/projects/GPU/sparse_GPU_analysis/spsolve_timings.py:19:23: F811 redefinition of unused 'lina' from line 1
#def single_test(A, y, lina):
#                      ^
#pySDC/projects/GPU/sparse_GPU_analysis/spsolve_timings.py:29:5: F811 redefinition of unused 'xp' from line 3
#    import numpy as xp
#    ^
#pySDC/projects/GPU/sparse_GPU_analysis/spsolve_timings.py:30:5: F811 redefinition of unused 'sp' from line 2
#    import scipy.sparse as sp
#    ^
#pySDC/projects/GPU/sparse_GPU_analysis/spsolve_timings.py:31:5: F811 redefinition of unused 'lina' from line 1
#    import scipy.sparse.linalg as lina
#    ^
#pySDC/projects/GPU/sparse_GPU_analysis/spsolve_timings.py:42:5: F811 redefinition of unused 'xp' from line 3
#    import cupy as xp
#    ^
#pySDC/projects/GPU/sparse_GPU_analysis/spsolve_timings.py:43:5: F811 redefinition of unused 'sp' from line 2
#    import cupyx.scipy.sparse as sp
#    ^
#pySDC/projects/GPU/sparse_GPU_analysis/spsolve_timings.py:44:5: F811 redefinition of unused 'lina' from line 1
#    import cupyx.scipy.sparse.linalg as lina
#    ^
#pySDC/projects/GPU/sparse_GPU_analysis/spsolve_timings.py:37:9: F841 local variable 'data' is assigned to but never used
#        data = {'CPU': times.cpu_times, 'GPU': times.gpu_times}
#        ^
#pySDC/projects/GPU/sparse_GPU_analysis/spsolve_timings.py:50:9: F841 local variable 'data' is assigned to but never used
#        data = {'CPU': times.cpu_times, 'GPU': times.gpu_times}
#        ^
#10    F811 redefinition of unused 'sp' from line 2
#2     F841 local variable 'data' is assigned to but never used
#12: