Plotting
#!!!!!!!!!! WARNING: RUFF FAILED !!!!!!!!!!: 

#pySDC/projects/RayleighBenard/analysis_scripts/plot_Nu.py:88:5: F811 Redefinition of unused `plot_Nu_over_time_Ra1e6` from line 68
#   |
#88 | def plot_Nu_over_time_Ra1e6():  # pragma: no cover
#   |     ^^^^^^^^^^^^^^^^^^^^^^^ F811
#89 |     Nu_fig, Nu_axs = plt.subplots(4, 1, sharex=True, sharey=True, figsize=figsize(scale=1, ratio=1.4))
#   |
#   = help: Remove definition: `plot_Nu_over_time_Ra1e6`
#
#pySDC/projects/RayleighBenard/analysis_scripts/plot_benchmarks.py:144:5: F841 Local variable `mask_block` is assigned to but never used
#    |
#143 |     mask_cyclic = data_Ra1e6_GPU.distribution == 'cyclic:cyclic:cyclic'
#144 |     mask_block = data_Ra1e6_GPU.distribution == 'block:cyclic:cyclic'
#    |     ^^^^^^^^^^ F841
#145 |     mask_time_parallel = data_Ra1e6_GPU.ntasks_time > 1
#146 |     mask = np.logical_and(mask_cyclic, mask_time_parallel)
#    |
#    = help: Remove assignment to unused variable `mask_block`
#
#pySDC/projects/RayleighBenard/analysis_scripts/plot_benchmarks.py:198:18: F541 [*] f-string without any placeholders
#    |
#196 |         ax.set_ylabel('time / s')
#197 |     fig.tight_layout()
#198 |     savefig(fig, f'pySDC_binding')
#    |                  ^^^^^^^^^^^^^^^^ F541
#    |
#    = help: Remove extraneous `f` prefix
#
#pySDC/projects/RayleighBenard/analysis_scripts/plot_benchmarks.py:261:9: F841 Local variable `norm` is assigned to but never used
#    |
#259 |     else:
#260 |         norm_data = None
#261 |         norm = 1
#    |         ^^^^ F841
#262 |
#263 |     for method in methods:
#    |
#    = help: Remove assignment to unused variable `norm`
#
#pySDC/projects/RayleighBenard/analysis_scripts/plot_benchmarks.py:275:9: F841 Local variable `finite_mask` is assigned to but never used
#    |
#273 |         mask = base_mask
#274 |
#275 |         finite_mask = np.logical_and(base_mask, np.isfinite(data.time))
#    |         ^^^^^^^^^^^ F841
#276 |         for _tasks_time in np.unique(data.ntasks_time):
#277 |             mask = np.logical_and(data.ntasks_time == _tasks_time, base_mask)
#    |
#    = help: Remove assignment to unused variable `finite_mask`: